version: '2'
services:
  php-fpm:
    build:
      context: php-fpm
    links:
      - mysql
      - redis
    volumes:
        - ${LOCAL_PATH}:${DOCKER_PATH}
        - ./php-fpm/conf.ini:/usr/local/etc/php/conf.d/conf.ini
    environment:
      XDEBUG_CONFIG: remote_host=${IP_ADDRESS}

  redis:
    image: redis
    ports:
      - 6379:6379

  nginx:
    image: nginx
    links:
      - php-fpm
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${LOCAL_PATH}:${DOCKER_PATH}
      - ./nginx/sites-available:/etc/nginx/sites-available
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /var/log/nginx:/var/log/nginx

#  postgres:
#    image: postgres
#    restart: always
#    volumes:
#      - ./data/postgresql:/var/lib/postgresql/data
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#    ports:
#      - 5432:5432

  mongodb:
      image: mongo
      environment:
        MONGO_DATA_DIR: ${MONGO_DATA_DIR}
        MONGODB_USER: ${MONGODB_USER}
        MONGODB_PASS: ${MONGODB_PASS}
      volumes:
        - ./data/mongodb:${MONGO_DATA_DIR}
      ports:
        - 27017:27017

  mysql:
    image: mysql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - "./data/mysql:/var/lib/mysql"
    ports:
      - 3306:3306

  adminer:
    image: adminer
    ports:
      - 8080:8080
