version: '3.3'

services:
    nginx:
        container_name: nginx
        build: nginx
        ports:
            - 10.5.0.1:80:80
            - 127.0.0.1:80:80
        links:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
            - ${APP_PATH}:/var/www
        networks:
            web_network:
                ipv4_address: 10.5.0.2

    php:
        container_name: phpfpm
        build:
            context: php/php8-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        networks:
            web_network:
                ipv4_address: 10.5.0.3
        volumes:
            - ${APP_PATH}:/var/www
            - ./logs/symfony:/var/www/symfony/app/logs
        links:
            - redis
            - dbmysql
        environment:
            XDEBUG_CONFIG: remote_host=${IP_ADDRESS}

    dbmysql:
        container_name: mysql
        image: mysql:8

        volumes:
            - ./dump:/dump
            - mysql_data_container:/var/lib/mysql
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            MYSQL_USER: ${DB_USER}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - 10.5.0.1:3306:3306
            - 127.0.0.1:3306:3306
        networks:
            web_network:
                ipv4_address: 10.5.0.4

#    dbpgsql:
#        container_name: pgsql
#        image: postgres:12
#        volumes:
#            - ./dump:/dump
#            - postgresql_data_container:/var/lib/postgresql
#            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#
#        environment:
#            POSTGRES_DB: ${DB}
#            POSTGRES_USER: ${DB_USER}
#            POSTGRES_PASSWORD: ${DB_PASSWORD}
#        ports:
#            - 10.5.0.1:5432:5432
#            - 127.0.0.1:5432:5432
#        networks:
#            web_network:
#                ipv4_address: 10.5.0.4

    redis:
        container_name: redis
        image: redis:alpine
        ports:
            - 10.5.0.1:6379:6379
            - 127.0.0.1:6379:6379
        networks:
            web_network:
                ipv4_address: 10.5.0.5

    rabbitmq:
        container_name: rabbitmq
        image: "rabbitmq:3-management"
        environment:
            RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
            RABBITMQ_DEFAULT_VHOST: "/"
        ports:
            - 10.5.0.1:15672:15672
            - 10.5.0.1:5672:5672
            - 127.0.0.1:15672:15672
            - 127.0.0.1:5672:5672
        labels:
            NAME: "rabbitmq1"
        networks:
            web_network:
                ipv4_address: 10.5.0.6

    adminer:
        container_name: adminer
        image: adminer
        ports:
            - 8080:8080
        networks:
            web_network:
                ipv4_address: 10.5.0.7

networks:
    web_network:
        driver: bridge
        ipam:
            config:
            - subnet: 10.5.0.0/16

volumes:
#    postgresql_data_container:
    mysql_data_container: