version: '2'

services:

    nginx:
        container_name: nginx
        build: nginx
        ports:
            - 80:80
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx

    php:
        container_name: phpfpm
        build:
            context: php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ${APP_PATH}:/var/www
            - ./logs/symfony:/var/www/symfony/app/logs
        links:
            - redis
            - dbpgsql
        environment:
            XDEBUG_CONFIG: remote_host=${IP_ADDRESS}

    dbpgsql:
        container_name: pgsql
        image: mdillon/postgis:latest
        volumes:
            - ./dump:/dump
            - postgresql_data_container:/var/lib/postgresql

        environment:
            POSTGRES_DB: ${DB}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - 5432:5432

    redis:
        container_name: redis
        image: redis:alpine
        ports:
            - 6379:6379

    adminer:
        container_name: adminer
        image: adminer
        ports:
            - 8080:8080

volumes:
    # mongodb_data_container:
    mysql_data_container:
    postgresql_data_container: